- name: Installing apache2
  apt: pkg={{ item }} state=latest
  with_items:
    - apache2
    - libapache2-mod-fastcgi
    - libapache2-mod-php7.0
  tags: apache2
  
- name: enabled mod_rewrite
  apache2_module: name=rewrite state=present
  notify:
    - restart apache2
    
- name: disable php5
  apache2_module: name=php5 state=absent
  ignore_errors: yes
  notify:
    - restart apache2 
  become: true 

- name: enable php7.0
  apache2_module: name=php7.0 state=present
  notify:
    - restart apache2 
  become: true   
    
- name: configure Apache2 Virtual hosts
  template: src=site.conf dest=/etc/apache2/sites-available/{{ item.name }}.conf
  with_items: vhosts
  when: item.name != "phpmyadmin.dev"
  notify:
    - restart apache2
  tags: apache2
  
- name: doing magic with phpmyadmin
  template: src=site.conf.pma dest=/etc/apache2/sites-available/{{ item.name }}.conf
  with_items: vhosts
  when: item.name == "phpmyadmin.dev"
  notify:
    - restart apache2
  tags: apache2  
  
- name: disable default site
  file: path=/etc/apache2/sites-enabled/000-default state=absent
  become: true
  notify:
    - restart apache2

- name: enable created sites
  file: src=/etc/apache2/sites-available/{{ item.name }}.conf dest=/etc/apache2/sites-enabled/{{ item.name }}.conf state=link
  with_items: vhosts
  notify:
    - restart apache2

- name: enabled actions
  apache2_module: name=actions state=present
  notify:
    - restart apache2
    
- name: enabled fastcgi
  apache2_module: name=fastcgi state=present
  notify:
    - restart apache2
  
- name: enabled alias
  apache2_module: name=alias state=present
  notify:
    - restart apache2

- name: adding some config
  copy: src=/vagrant/provisioning/roles/apache2/templates/server.conf dest=/etc/apache2/conf-enabled/server.conf
  become: true
  notify:
    - restart apache2
