# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.repository.exam:
        class: AppBundle\Repository\ExamRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - 'AppBundle\Entity\Exam'

    app.repository.question:
        class: AppBundle\Repository\QuestionRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - 'AppBundle\Entity\Question'

    app.repository.user:
        class: AppBundle\Repository\UserRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - 'AppBundle\Entity\User'

    app.repository.score:
            class: AppBundle\Repository\ScoreRepository
            factory: ['@doctrine.orm.default_entity_manager', getRepository]
            arguments:
                - 'AppBundle\Entity\Score'

    app.exam.provider:
        class: AppBundle\Service\Exam\ExamProvider
        arguments:
            - '@app.repository.exam'

    app.question.provider:
        class: AppBundle\Service\Question\QuestionProvider
        arguments:
            - '@app.repository.question'

    app.exam.creator:
        class: AppBundle\Service\Exam\ExamCreator
        arguments:
            - '@app.repository.exam'

    app.question.creator:
        class: AppBundle\Service\Question\QuestionCreator
        arguments:
            - '@app.repository.question'

    app.service.password_service:
        class: AppBundle\Service\Security\PasswordService
        arguments:
            - '@security.password_encoder'

    app.service.user_creator:
        class: AppBundle\Service\User\UserCreator
        arguments:
            - '@app.service.password_service'
            - '@app.repository.user'

    app.user.provider:
        class: AppBundle\Service\User\UserProvider
        arguments:
            - '@app.repository.user'

    app.exam.updater:
        class: AppBundle\Service\Exam\ExamUpdater
        arguments:
            - '@app.repository.exam'
            - '@app.repository.user'
            - '@app.repository.question'

    app.handler.user:
        class: AppBundle\Service\User\UserHandler
        arguments:
            - '@app.service.user_creator'

    app.service.user_remover:
        class: AppBundle\Service\User\UserRemover
        arguments:
            - '@app.repository.user'

    app.score_provider:
        class: AppBundle\Service\Exam\ScoreProvider
        arguments:
            - '@app.repository.score'

    app.score_creator:
        class: AppBundle\Service\Exam\ScoreCreator
        arguments:
            - '@app.repository.score'

    app.score_handler:
        class: AppBundle\Service\Exam\ScoreHandler
        arguments:
            - '@app.score_creator'

